services:

  op-reth: 
    image:  ghcr.io/otternode-io/ott-op-stack-1103 
    restart: always
    user: root
    entrypoint: /op-reth-entrypoint
    volumes:
        - ./data/op-reth:/datadir
        - ../config:/config
        - ./op-reth-entrypoint:/op-reth-entrypoint
    env_file:
      - ../config/.env
    ports:
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  op-node: 
    image:  ghcr.io/otternode-io/ott-op-stack-1103 
    restart: always
    user: root
    depends_on:
      - op-reth
    entrypoint: /op-node-entrypoint
    volumes:
        - ../config:/config
        - ./op-node-entrypoint:/op-node-entrypoint
        - ./data:/data
        - ./data/op_log:/op_log
    env_file:
      - ../config/.env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

